# Generated by Django 3.2.12 on 2023-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_petition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_categorynum', models.CharField(max_length=50)),
                ('s_categoryname', models.CharField(max_length=50)),
                ('s_title', models.TextField()),
                ('s_content', models.TextField()),
                ('s_like', models.IntegerField()),
                ('s_mean', models.IntegerField()),
            ],
        ),
    ]
